version: "3.6"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest' 
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'http://localhost'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - ./gitlab_config:/etc/gitlab
      - ./gitlab_logs:/var/log/gitlab
      - ./gitlab_data:/var/opt/gitlab
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          memory: 4G 

  jenkins:
    image: jenkins/jenkins:latest
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/jenkins_home
      - ./jenkins_var:/var
    depends_on:
      - gitlab
      - sonarqube
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
        reservations:
          memory: 1G 

  sonarqube:
    image: sonarqube:lts-community
    restart: always
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 4G
        reservations:
          memory: 2G 
    
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  jenkins: